##mysql config
spring:
  datasource:
    url: jdbc:mysql://192.168.0.103/employee
    username: root
    password: 660708
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
 ########################################################
 ###FREEMARKER (FreeMarkerAutoConfiguration)
 ########################################################
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
#server config setting
server:
  port: 8081
  servlet:
    context-path: /login
#\u542F\u7528shutdown
management:
   endpoints:
    web:
      exposure:
        include: ["shutdown"]
   endpoint:
      shutdown:
        enabled: true

#mybatis_config
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.demo.demologin.entity
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.demo.demologin.entity
